title: "Priyadarshini Chettiar"
email: priyadarshinichettiar@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  I'm a Programming Enthusiast. I love flutter and Javascript
baseurl: "/" 
url: "https://priyadarshu.github.io" 
twitter_username: priya_darshu_
github_username:  priyadarshu

sass:
  sass_dir: _sass

icon: ./assets/img/icon.jpg
